import type { ParsedEvent } from './parser'

/** Options for Markdown export generation. */
export interface MdExportOptions {
  layout: 'table' | 'list'
  includeWarnings: boolean
}

/** Month abbreviations for human-readable date formatting. */
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

/**
 * Format a YYYY-MM-DD date as "Mon DD" (e.g., "Mar 15").
 */
function formatHumanDate(dateStr: string | null): string {
  if (!dateStr) return '—'
  const [, m, d] = dateStr.split('-').map(Number)
  return `${MONTHS[m - 1]} ${d}`
}

/**
 * Escape pipe characters in table cells.
 */
function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|')
}

/**
 * Generate table-format Markdown output.
 */
function generateTable(events: ParsedEvent[], options: MdExportOptions): string[] {
  const lines: string[] = []

  // Table header
  lines.push('| # | Event | Start | End | Location | Status |')
  lines.push('|---|-------|-------|-----|----------|--------|')

  // Table rows
  events.forEach((event, i) => {
    const row = [
      String(i + 1),
      escapeCell(event.name),
      formatHumanDate(event.startDate),
      formatHumanDate(event.endDate),
      escapeCell(event.location ?? '—'),
      escapeCell(event.status ?? '—'),
    ]
    lines.push(`| ${row.join(' | ')} |`)

    if (options.includeWarnings && event.warnings.length > 0) {
      for (const w of event.warnings) {
        lines.push(`| | ⚠ ${escapeCell(w.field)}: ${escapeCell(w.message)} | | | | |`)
      }
    }
  })

  return lines
}

/**
 * Generate list-format Markdown output.
 */
function generateList(events: ParsedEvent[], options: MdExportOptions): string[] {
  const lines: string[] = []

  events.forEach((event, i) => {
    lines.push(`${i + 1}. **${event.name}**`)
    if (event.startDate) {
      const end = event.endDate ? ` – ${formatHumanDate(event.endDate)}` : ''
      lines.push(`   - **Date:** ${formatHumanDate(event.startDate)}${end}`)
    }
    if (event.location) lines.push(`   - **Location:** ${event.location}`)
    if (event.status) lines.push(`   - **Status:** ${event.status}`)

    if (options.includeWarnings && event.warnings.length > 0) {
      for (const w of event.warnings) {
        lines.push(`   - ⚠ ${w.field}: ${w.message}`)
      }
    }

    lines.push('')
  })

  return lines
}

/**
 * Generate Markdown output from selected parsed events.
 * Supports table or list layout with optional warning display.
 */
export function generateMd(
  events: ParsedEvent[],
  options: MdExportOptions,
  templateName?: string | null,
): string {
  const selected = events.filter((e) => e.isSelected)
  const now = new Date()
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`

  const lines: string[] = []

  // Header
  const title = templateName ?? 'ScrapeGoat Export'
  lines.push(`# ${title}`)
  lines.push(`*Exported via ScrapeGoat on ${dateStr}*`)
  lines.push('')

  // Body
  if (options.layout === 'table') {
    lines.push(...generateTable(selected, options))
  } else {
    lines.push(...generateList(selected, options))
  }

  // Footer
  lines.push('')
  lines.push('---')
  lines.push(`*${selected.length} event${selected.length !== 1 ? 's' : ''} · Generated by [ScrapeGoat](https://scrapegoat.io)*`)
  lines.push('')

  return lines.join('\n')
}

/** Default Markdown export options. */
export const DEFAULT_MD_OPTIONS: MdExportOptions = {
  layout: 'table',
  includeWarnings: false,
}
