import { describe, it, expect } from 'vitest'
import { generateIcs, DEFAULT_ICS_OPTIONS } from '../exportIcs'
import type { IcsExportOptions } from '../exportIcs'
import type { ParsedEvent } from '../parser'

/** Factory for test events. */
function makeEvent(overrides: Partial<ParsedEvent> = {}): ParsedEvent {
  return {
    id: 'sha256-abc123',
    name: 'ACME Trade Show',
    startDate: '2026-03-15',
    endDate: '2026-03-18',
    moveInDate: '2026-03-13',
    moveOutDate: '2026-03-20',
    location: 'Hall A',
    status: 'Confirmed',
    customFields: {},
    rawText: 'raw text here',
    warnings: [],
    isSelected: true,
    ...overrides,
  }
}

describe('generateIcs', () => {
  it('produces a valid VCALENDAR wrapper', () => {
    const result = generateIcs([makeEvent()], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('BEGIN:VCALENDAR')
    expect(result).toContain('END:VCALENDAR')
    expect(result).toContain('VERSION:2.0')
    expect(result).toContain('PRODID:-//ScrapeGoat//PDF Calendar Extractor//EN')
    expect(result).toContain('CALSCALE:GREGORIAN')
    expect(result).toContain('METHOD:PUBLISH')
  })

  it('uses CRLF line endings', () => {
    const result = generateIcs([makeEvent()], DEFAULT_ICS_OPTIONS)
    // Every line should end with \r\n
    const lines = result.split('\r\n')
    expect(lines.length).toBeGreaterThan(5)
    // No bare \n without \r
    expect(result.replace(/\r\n/g, '')).not.toContain('\n')
  })

  it('includes VTIMEZONE block', () => {
    const result = generateIcs([makeEvent()], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('BEGIN:VTIMEZONE')
    expect(result).toContain('TZID:America/New_York')
    expect(result).toContain('END:VTIMEZONE')
    expect(result).toContain('BEGIN:STANDARD')
    expect(result).toContain('BEGIN:DAYLIGHT')
  })

  it('includes X-WR-TIMEZONE and optional X-WR-CALNAME', () => {
    const result = generateIcs([makeEvent()], DEFAULT_ICS_OPTIONS, 'Test Calendar')
    expect(result).toContain('X-WR-TIMEZONE:America/New_York')
    expect(result).toContain('X-WR-CALNAME:Test Calendar')
  })

  it('generates multi-phase VEVENTs when multiPhase is true', () => {
    const result = generateIcs([makeEvent()], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('SUMMARY:ACME Trade Show (Move-In)')
    expect(result).toContain('SUMMARY:ACME Trade Show (Event)')
    expect(result).toContain('SUMMARY:ACME Trade Show (Move-Out)')
  })

  it('generates single VEVENT when multiPhase is false', () => {
    const opts: IcsExportOptions = {
      ...DEFAULT_ICS_OPTIONS,
      multiPhase: false,
    }
    const result = generateIcs([makeEvent()], opts)
    expect(result).toContain('SUMMARY:ACME Trade Show')
    expect(result).not.toContain('(Move-In)')
    expect(result).not.toContain('(Event)')
    expect(result).not.toContain('(Move-Out)')
  })

  it('uses VALUE=DATE format for dates', () => {
    const result = generateIcs([makeEvent()], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).toContain('DTSTART;VALUE=DATE:20260315')
  })

  it('makes DTEND exclusive (adds 1 day)', () => {
    const result = generateIcs([makeEvent()], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    // endDate is 2026-03-18, DTEND should be 2026-03-19
    expect(result).toContain('DTEND;VALUE=DATE:20260319')
  })

  it('maps status: Confirmed → CONFIRMED', () => {
    const result = generateIcs([makeEvent()], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('STATUS:CONFIRMED')
  })

  it('maps status: Tentative → TENTATIVE', () => {
    const result = generateIcs([makeEvent({ status: 'Tentative' })], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('STATUS:TENTATIVE')
  })

  it('maps status: Canceled → CANCELLED', () => {
    const result = generateIcs([makeEvent({ status: 'Canceled' })], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('STATUS:CANCELLED')
  })

  it('generates UID with @scrapegoat suffix', () => {
    const result = generateIcs([makeEvent()], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).toContain('UID:sha256-abc123@scrapegoat')
  })

  it('generates phase-specific UIDs in multi-phase mode', () => {
    const result = generateIcs([makeEvent()], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('UID:sha256-abc123-movein@scrapegoat')
    expect(result).toContain('UID:sha256-abc123-event@scrapegoat')
    expect(result).toContain('UID:sha256-abc123-moveout@scrapegoat')
  })

  it('includes LOCATION and DESCRIPTION', () => {
    const result = generateIcs([makeEvent()], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).toContain('LOCATION:Hall A')
    expect(result).toContain('DESCRIPTION:Location: Hall A\\nStatus: Confirmed\\n\\nGenerated by ScrapeGoat')
  })

  it('skips unselected events', () => {
    const events = [makeEvent(), makeEvent({ id: 'skipped', name: 'Skipped', isSelected: false })]
    const result = generateIcs(events, { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).toContain('SUMMARY:ACME Trade Show')
    expect(result).not.toContain('SUMMARY:Skipped')
  })

  it('respects phase include toggles', () => {
    const opts: IcsExportOptions = {
      ...DEFAULT_ICS_OPTIONS,
      includePhases: { moveIn: false, event: true, moveOut: false },
    }
    const result = generateIcs([makeEvent()], opts)
    expect(result).not.toContain('(Move-In)')
    expect(result).toContain('(Event)')
    expect(result).not.toContain('(Move-Out)')
  })

  it('handles event without endDate', () => {
    const event = makeEvent({ endDate: null })
    const result = generateIcs([event], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    // DTEND should be startDate + 1 day
    expect(result).toContain('DTEND;VALUE=DATE:20260316')
  })

  it('handles event without location or status', () => {
    const event = makeEvent({ location: null, status: null })
    const result = generateIcs([event], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).not.toContain('LOCATION:')
    expect(result).not.toContain('STATUS:')
  })

  it('folds long lines at 75 octets', () => {
    const longName = 'A'.repeat(100)
    const event = makeEvent({ name: longName })
    const result = generateIcs([event], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    const lines = result.split('\r\n')
    for (const line of lines) {
      const bytes = new TextEncoder().encode(line)
      expect(bytes.length).toBeLessThanOrEqual(75)
    }
  })

  it('produces empty calendar when no events are selected', () => {
    const event = makeEvent({ isSelected: false })
    const result = generateIcs([event], DEFAULT_ICS_OPTIONS)
    expect(result).toContain('BEGIN:VCALENDAR')
    expect(result).toContain('END:VCALENDAR')
    expect(result).not.toContain('BEGIN:VEVENT')
  })

  it('uses UTC timezone without daylight block', () => {
    const opts: IcsExportOptions = { ...DEFAULT_ICS_OPTIONS, timezone: 'UTC' }
    const result = generateIcs([makeEvent()], opts)
    expect(result).toContain('TZID:UTC')
    expect(result).not.toContain('BEGIN:DAYLIGHT')
  })

  it('escapes semicolons, commas, and backslashes in TEXT fields per RFC 5545', () => {
    const event = makeEvent({ name: 'Meet & Greet; VIP', location: 'Hall A, Room 1\\2' })
    const result = generateIcs([event], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).toContain('SUMMARY:Meet & Greet\\; VIP')
    expect(result).toContain('LOCATION:Hall A\\, Room 1\\\\2')
  })

  it('falls back to moveInDate when startDate is null (single-phase)', () => {
    const event = makeEvent({ startDate: null, endDate: null, moveInDate: '2026-03-10' })
    const result = generateIcs([event], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).toContain('BEGIN:VEVENT')
    expect(result).toContain('DTSTART;VALUE=DATE:20260310')
  })

  it('falls back to moveOutDate when startDate and moveInDate are null', () => {
    const event = makeEvent({ startDate: null, endDate: null, moveInDate: null, moveOutDate: '2026-03-25' })
    const result = generateIcs([event], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).toContain('BEGIN:VEVENT')
    expect(result).toContain('DTSTART;VALUE=DATE:20260325')
  })

  it('skips event with no dates at all', () => {
    const event = makeEvent({ startDate: null, endDate: null, moveInDate: null, moveOutDate: null })
    const result = generateIcs([event], { ...DEFAULT_ICS_OPTIONS, multiPhase: false })
    expect(result).not.toContain('BEGIN:VEVENT')
  })
})
