import { describe, it, expect, vi } from 'vitest'
import { generateMd, DEFAULT_MD_OPTIONS } from '../exportMd'
import type { MdExportOptions } from '../exportMd'
import type { ParsedEvent } from '../parser'

function makeEvent(overrides: Partial<ParsedEvent> = {}): ParsedEvent {
  return {
    id: 'sha256-abc123',
    name: 'ACME Trade Show',
    startDate: '2026-03-15',
    endDate: '2026-03-18',
    moveInDate: '2026-03-13',
    moveOutDate: '2026-03-20',
    location: 'Hall A',
    status: 'Confirmed',
    customFields: {},
    rawText: 'raw text',
    warnings: [],
    isSelected: true,
    ...overrides,
  }
}

describe('generateMd', () => {
  it('includes header with template name', () => {
    const result = generateMd([makeEvent()], DEFAULT_MD_OPTIONS, 'Javits Center Events')
    expect(result).toContain('# Javits Center Events')
    expect(result).toContain('*Exported via ScrapeGoat on')
  })

  it('uses default title when no template name', () => {
    const result = generateMd([makeEvent()], DEFAULT_MD_OPTIONS)
    expect(result).toContain('# ScrapeGoat Export')
  })

  it('generates GFM table by default', () => {
    const result = generateMd([makeEvent()], DEFAULT_MD_OPTIONS)
    expect(result).toContain('| # | Event | Start | End | Location | Status |')
    expect(result).toContain('|---|-------|-------|-----|----------|--------|')
    expect(result).toContain('| 1 | ACME Trade Show | Mar 15 | Mar 18 | Hall A | Confirmed |')
  })

  it('generates list format when layout is list', () => {
    const opts: MdExportOptions = { layout: 'list', includeWarnings: false }
    const result = generateMd([makeEvent()], opts)
    expect(result).toContain('1. **ACME Trade Show**')
    expect(result).toContain('   - **Date:** Mar 15 – Mar 18')
    expect(result).toContain('   - **Location:** Hall A')
    expect(result).toContain('   - **Status:** Confirmed')
  })

  it('includes footer with event count and attribution', () => {
    const result = generateMd([makeEvent()], DEFAULT_MD_OPTIONS)
    expect(result).toContain('*1 event · Generated by [ScrapeGoat](https://scrapegoat.io)*')
  })

  it('shows em-dash for null fields in table', () => {
    const event = makeEvent({ location: null, status: null, endDate: null })
    const result = generateMd([event], DEFAULT_MD_OPTIONS)
    expect(result).toContain('| 1 | ACME Trade Show | Mar 15 | — | — | — |')
  })

  it('skips unselected events', () => {
    const events = [
      makeEvent(),
      makeEvent({ id: 'b', name: 'Skipped', isSelected: false }),
    ]
    const result = generateMd(events, DEFAULT_MD_OPTIONS)
    expect(result).toContain('ACME Trade Show')
    expect(result).not.toContain('Skipped')
  })

  it('includes warnings in table when option is set', () => {
    const event = makeEvent({
      warnings: [{ field: 'endDate', message: 'Ambiguous date', rawValue: '3/18', suggestion: '2026-03-18' }],
    })
    const opts: MdExportOptions = { layout: 'table', includeWarnings: true }
    const result = generateMd([event], opts)
    expect(result).toContain('⚠ endDate: Ambiguous date')
  })

  it('includes warnings in list when option is set', () => {
    const event = makeEvent({
      warnings: [{ field: 'endDate', message: 'Ambiguous date', rawValue: '3/18', suggestion: '2026-03-18' }],
    })
    const opts: MdExportOptions = { layout: 'list', includeWarnings: true }
    const result = generateMd([event], opts)
    expect(result).toContain('⚠ endDate: Ambiguous date')
  })

  it('excludes warnings by default', () => {
    const event = makeEvent({
      warnings: [{ field: 'endDate', message: 'Ambiguous date', rawValue: '3/18', suggestion: '2026-03-18' }],
    })
    const result = generateMd([event], DEFAULT_MD_OPTIONS)
    expect(result).not.toContain('⚠')
  })

  it('escapes pipe characters in event names', () => {
    const event = makeEvent({ name: 'Event | With | Pipes' })
    const result = generateMd([event], DEFAULT_MD_OPTIONS)
    expect(result).toContain('Event \\| With \\| Pipes')
  })

  it('formats human-readable dates correctly', () => {
    const event = makeEvent({ startDate: '2026-01-01', endDate: '2026-12-31' })
    const result = generateMd([event], DEFAULT_MD_OPTIONS)
    expect(result).toContain('Jan 1')
    expect(result).toContain('Dec 31')
  })

  it('handles list format with no endDate', () => {
    const event = makeEvent({ endDate: null })
    const opts: MdExportOptions = { layout: 'list', includeWarnings: false }
    const result = generateMd([event], opts)
    expect(result).toContain('   - **Date:** Mar 15')
    expect(result).not.toContain('–')
  })

  it('omits location/status in list when null', () => {
    const event = makeEvent({ location: null, status: null })
    const opts: MdExportOptions = { layout: 'list', includeWarnings: false }
    const result = generateMd([event], opts)
    expect(result).not.toContain('**Location:**')
    expect(result).not.toContain('**Status:**')
  })

  it('pluralizes footer correctly for multiple events', () => {
    const events = [
      makeEvent({ id: 'a', name: 'First' }),
      makeEvent({ id: 'b', name: 'Second' }),
    ]
    const result = generateMd(events, DEFAULT_MD_OPTIONS)
    expect(result).toContain('*2 events · Generated by')
  })

  it('numbers multiple events correctly', () => {
    const events = [
      makeEvent({ id: 'a', name: 'First' }),
      makeEvent({ id: 'b', name: 'Second' }),
      makeEvent({ id: 'c', name: 'Third' }),
    ]
    const result = generateMd(events, DEFAULT_MD_OPTIONS)
    expect(result).toContain('| 1 | First')
    expect(result).toContain('| 2 | Second')
    expect(result).toContain('| 3 | Third')
  })
})
